In [142]:
import numpy as np

In [143]:
minha_lista =[1, 2, 3]

In [144]:
minha_lista

[1, 2, 3]

In [145]:
np.array(minha_lista)

array([1, 2, 3])

In [146]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [147]:
np.array(minha_matriz) #matriz de 2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
np.arange(0, 10) # vetor 10 elementos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.arange(0, 10, 2) #pares

array([0, 2, 4, 6, 8])

In [150]:
np.zeros(3) # 3 zeros

array([0., 0., 0.])

In [151]:
arr = np.zeros(3)

In [152]:
arr

array([0., 0., 0.])

In [153]:
arr = np.zeros((5, 5)) #matriz 5x5 zerada

In [154]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [155]:
np.ones((3, 3)) #matriz de uns 3x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [156]:
np.eye(4) #matriz identidade 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [157]:
np.linspace (0, 10, 2) #vetor distrib. uniforme

array([ 0., 10.])

In [158]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [159]:
np.random.rand(5) #numeros randomicos

array([0.04744281, 0.79351421, 0.0678671 , 0.35658898, 0.88474787])

In [160]:
np.random.rand(5) * 100

array([62.81609937, 60.55259128, 71.62773924,  4.1013815 , 79.24821255])

In [161]:
np.random.rand (5, 4, 3) #gera vetor aleatorio 5 blocos, 4 linhas 3 colunas

array([[[0.06595027, 0.28338513, 0.58731514],
        [0.22620034, 0.92221871, 0.87586519],
        [0.9712634 , 0.90687419, 0.20742175],
        [0.81290624, 0.11502427, 0.88525703]],

       [[0.20685996, 0.32922217, 0.70124207],
        [0.00382961, 0.57131567, 0.21131964],
        [0.65190425, 0.85794037, 0.95014652],
        [0.05876018, 0.75648602, 0.21087461]],

       [[0.73991087, 0.60069756, 0.45351924],
        [0.04805445, 0.0842261 , 0.16827416],
        [0.21309506, 0.93451896, 0.12023862],
        [0.12552214, 0.29929187, 0.41088196]],

       [[0.52313598, 0.10716881, 0.95127918],
        [0.70775733, 0.49816747, 0.17004776],
        [0.92906862, 0.17244237, 0.58120751],
        [0.07752337, 0.12255956, 0.35581887]],

       [[0.30543008, 0.75312638, 0.30921366],
        [0.649143  , 0.85034119, 0.98403849],
        [0.0879159 , 0.21141815, 0.90356009],
        [0.06454867, 0.2755308 , 0.04849896]]])

In [162]:
np.random.randn(4) #usa distrib. gausiana

array([ 1.10737518, -1.29808423,  0.69590872, -0.37838597])

In [163]:
np.random.randint (0, 100, 10) #10 numeros entre 0 e 99

array([26, 64, 18,  8, 11, 60, 94, 72, 94, 70], dtype=int32)

In [164]:
np.random.rand(5) * 100

array([15.58217217, 64.34895907, 80.20730716, 20.91011682, 59.94749055])

In [165]:
np.round(np.random.rand(5) * 100, 0) # 5 num aleatorio e arredonda

array([ 4., 36., 61., 47., 36.])

In [166]:
arr = np.random.rand(25) #vetor de tam 25

In [167]:
arr

array([0.19690316, 0.08069863, 0.91317452, 0.90802806, 0.16315282,
       0.1352747 , 0.91979442, 0.41269881, 0.06675602, 0.87682841,
       0.30659799, 0.99463732, 0.26257218, 0.84281745, 0.14159402,
       0.73995531, 0.67105098, 0.59237796, 0.00985462, 0.3923458 ,
       0.26339182, 0.20114672, 0.61234943, 0.81527841, 0.67745474])

In [168]:
arr.reshape((5,5)) #muda para 5x5, mas nao atribui ao arr

array([[0.19690316, 0.08069863, 0.91317452, 0.90802806, 0.16315282],
       [0.1352747 , 0.91979442, 0.41269881, 0.06675602, 0.87682841],
       [0.30659799, 0.99463732, 0.26257218, 0.84281745, 0.14159402],
       [0.73995531, 0.67105098, 0.59237796, 0.00985462, 0.3923458 ],
       [0.26339182, 0.20114672, 0.61234943, 0.81527841, 0.67745474]])

In [169]:
arr = arr.reshape((5,5)) #muda para 5x5 e atribui ao arr

In [170]:
arr

array([[0.19690316, 0.08069863, 0.91317452, 0.90802806, 0.16315282],
       [0.1352747 , 0.91979442, 0.41269881, 0.06675602, 0.87682841],
       [0.30659799, 0.99463732, 0.26257218, 0.84281745, 0.14159402],
       [0.73995531, 0.67105098, 0.59237796, 0.00985462, 0.3923458 ],
       [0.26339182, 0.20114672, 0.61234943, 0.81527841, 0.67745474]])

In [171]:
arr.shape

(5, 5)

In [172]:
arr.max() #maiorvalor matriz

np.float64(0.9946373190591685)

In [173]:
arr.min() #menor vlaor da matriz

np.float64(0.009854621653616946)

In [174]:
arr.argmax() #index onde o maior elemento esta

np.int64(11)

In [199]:
arr.argmin() #index onde o menor elemento esta

np.int64(0)

In [ ]:
Indexação e fatiamento de arrays

In [176]:
arr = np.arange(0, 30, 3)

In [177]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [178]:
arr[3]

np.int64(9)

In [179]:
arr[2:5] #multiplos elementos

array([ 6,  9, 12])

In [180]:
arr[:5] #todos elem até o 5

array([ 0,  3,  6,  9, 12])

In [181]:
arr [2:] #extrai subarray ate o 27

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [182]:
arr[2:]=100

In [183]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [184]:
arr = np.arange(50).reshape(5, 10) #gera vetor 1 a 0, reshapando para matriz de 5x10

In [185]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [186]:
arr.shape

(5, 10)

In [187]:
arr2 = arr[:3]

In [188]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [189]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [190]:
arr2 = arr[:3].copy()

In [191]:
arr [1:4, 5:] 

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [192]:
bol = arr > 50

In [193]:
arr[bol]

array([], dtype=int64)

In [194]:
array = np.linspace(0, 100, 30) #30 numeros espaçados igualmente

In [195]:
array.shape

(30,)

In [196]:
array = array.reshape(3, 10) #reorganiza matriz de 3 linhas 10 colunas

In [197]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [198]:
array [0:2, 2]

array([ 6.89655172, 41.37931034])

Operações com NUMPY

In [202]:
arr = np.arange(0, 16) # - 0 a 15

In [203]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [207]:
arr + arr #soma

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [208]:
arr - arr #subtrai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [211]:
arr * arr #multiplica

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [210]:
arr / arr #encontrou uma divisão incorreta, mas ainda assim retornou a resposta

C:\Users\igwin\AppData\Local\Temp\ipykernel_8196\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [214]:
1 / 0 #erro, não retorna nada

ZeroDivisionError: division by zero

In [217]:
1 / arr #um dos valores retorna infinito (divis por 0)

C:\Users\igwin\AppData\Local\Temp\ipykernel_8196\3788549396.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr #um dos valores retorna infinito (divis por 0)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [219]:
arr ** 2 #exponenciacao

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [221]:
arr + 100 #soma todos os valores do elemento

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [226]:
arr - 100 #subtrai todos os elementos

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [227]:
arr * 100 #multiplica todos os elementos

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [230]:
np.sqrt (arr) #raiz quadrada de todos os elementos

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [232]:
np.exp(arr) #mesmo caso com exponenciacao

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [234]:
np.mean(arr) #faz a media

np.float64(7.5)

In [236]:
np.std(arr) #desvvio padrao

np.float64(4.6097722286464435)

In [239]:
np.sin(arr) #seno dos elementos

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [243]:
np.max(arr) #maior valor do array

np.int64(15)

In [244]:
np.min(arr) #menor valor do array

np.int64(0)