***Exercícios resolvidos numpy***

In [3]:
import numpy as np #importa numpy com abreviatura np

In [5]:
np.zeros(10) #matriz de 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10) #matriz de 10 uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10) * 5 #matriz de 10 cincos (nao exxiste np.fives)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.arange(10, 51) #matriz 10 a 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
np.arange(10, 51, 2) #array de numeros pares de 10 até 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
np.arange(0,9).reshape (3,3)##cria matriz 3x3 com valores de 0 a 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.eye(3)#matriz identity 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand (1) #numeros aleatorios entre 0 e 1

array([0.30144399])

In [16]:
np.random.randn(25)#gera um array de 25 num aleatorios de uma distribuição normal

array([-1.19890253, -0.07438108, -0.63191146,  0.34954568, -0.75517334,
       -0.9521053 , -0.05357914,  0.07886544, -0.7461794 , -1.88913528,
        0.85604898, -0.15187265,  2.14322979, -1.3476524 ,  0.55978581,
        0.33154532,  2.79176687, -0.06659103, -0.07109561,  1.29944438,
       -0.19037639,  0.32553172, -0.91845058,  0.11055567, -0.73995112])

In [18]:
np.arange(0, 101) / 100 #criado uma matriz associado a uma op. escalar

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [19]:
np.linspace(0,1,20)# array de tam.20 igualmente espaçado entre 0 e 1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

replicação de matrizes conforme está na questão:

In [23]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
mat[3, -1]#elem 20 da matriz

np.int64(20)

In [28]:
mat[:3,1]#puxa apenas a segunda coluna com os 3 elementos apresentados

array([ 2,  7, 12])

In [30]:
mat [-1, :]#ultima linha da matriz como vetor

array([21, 22, 23, 24, 25])

In [32]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
mat.sum()#soma de todos os valores no mat

np.int64(325)

In [37]:
np.std(mat) #desvio padrao dos valores em mat

np.float64(7.211102550927978)

In [40]:
mat.sum(axis=0) #obtem soma de todas as colunas em mat

array([55, 60, 65, 70, 75])